"""Compiles shaders/ssao_mask.hlsl into ao_shader.h, the ambient occlusion shader of NierReplicantGFX.

The plugin creates this shader in place of the game's gen_ssao_mask_default_c when FIX_AO_SHADER is set.
The source is compiled twice with different STRENGTH values; the only dword that differs is where the
plugin writes the Strength setting. The header holds the bytecode with STRENGTH = 1.0 and that offset.

Usage:
  python gen_ao_shader.py [--out ao_shader.h] [--check]
    --check   create the shader on a WARP Direct3D 11 device
"""
import argparse
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import d3dcheck  # noqa: E402
import dxbc  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "shaders" / "ssao_mask.hlsl"
REPLACES = "gen_ssao_mask_default_c"
FIX_AO_SHADER = 32
D3DCOMPILE_OPTIMIZATION_LEVEL3 = 1 << 15
PROBES = (1.25, 1.75)        # neither 1 nor 2, so the compiler keeps a plain multiply


def build():
    """(bytecode with STRENGTH = 1.0, byte offset of STRENGTH), or exits with the compiler messages."""
    blobs = []
    for value in PROBES:
        blob, messages = d3dcheck.compile_hlsl(SOURCE.read_bytes(), SOURCE.name, "main", "cs_5_0",
                                               D3DCOMPILE_OPTIMIZATION_LEVEL3, {"STRENGTH": value})
        if messages:
            print(messages.rstrip())
        if blob is None:
            sys.exit(1)
        blobs.append(bytearray(blob))
    a, b = blobs
    assert len(a) == len(b), "STRENGTH changed the code size"
    diff = [i for i in range(20, len(a), 4) if a[i:i + 4] != b[i:i + 4]]
    assert len(diff) == 1, f"STRENGTH found at {len(diff)} places"
    at = diff[0]
    assert struct.unpack_from("<f", a, at)[0] == PROBES[0] and struct.unpack_from("<f", b, at)[0] == PROBES[1]
    struct.pack_into("<f", a, at, 1.0)
    a[4:20] = dxbc.checksum(a)
    return bytes(a), at


def header(blob, at):
    lines = ["/* Generated by tools/gen_ao_shader.py from shaders/ssao_mask.hlsl (cs_5_0). */",
             "#pragma once", "#include <stdint.h>", "",
             f"#define FIX_AO_SHADER        {FIX_AO_SHADER}",
             f'#define AO_SHADER_REPLACES   "{REPLACES}"',
             f"#define AO_SHADER_STRENGTH   0x{at:x}   /* byte offset of the STRENGTH float */", "",
             f"static const uint8_t AO_SHADER[{len(blob)}] = {{"]
    for i in range(0, len(blob), 16):
        lines.append("    " + " ".join(f"0x{v:02x}," for v in blob[i:i + 16]))
    lines.append("};")
    return "\n".join(lines) + "\n"


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(ROOT / "ao_shader.h"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    blob, at = build()
    Path(args.out).write_text(header(blob, at), encoding="utf-8")
    print(f"{args.out}: {len(blob)} bytes, STRENGTH at 0x{at:x}")
    if args.check:
        disassemble, create = d3dcheck.d3d()
        hr = create(blob, True)
        slots = next((l for l in (disassemble(blob) or "").splitlines() if "instruction slots used" in l), "")
        print(f"{'ok  ' if hr == 0 else 'FAIL'} CreateComputeShader 0x{hr:08x}; {slots.strip('/ ')}")
        return 0 if hr == 0 else 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
